Question 1
Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [9]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
# Addition 
print(arr1+2)

# Multiplication
print(arr1*3)

# Divide
print(arr1/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Question 2 
Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [10]:
arr2 = np.array([1,2,3,4,5,6])
reversed_arr = arr2[::-1]
print(reversed_arr)

def most_frequent(array):
    unique, counts = np.unique(array, return_counts=True)  
    most_frequent_value = unique[np.argmax(counts)] 
    indices = np.where(array == most_frequent_value)[0]  
    return most_frequent_value, indices

# (i) For x array
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_x, indices_x = most_frequent(x)
print("Most frequent value in x:", most_frequent_x)
print("Indices:", indices_x)

# (ii) For y array
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_y, indices_y = most_frequent(y)
print("Most frequent value in y:", most_frequent_y)
print("Indices:", indices_y)


[6 5 4 3 2 1]
Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


Question 3 
Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [11]:
arr3 = np.array([
    [10, 20, 30], 
    [40, 50, 60], 
    [70, 80, 90]
])

element_a = arr3[0, 1]  
element_b = arr3[2, 0]  

print("Element at 1st row, 2nd column:", element_a)
print("Element at 3rd row, 1st column:", element_b)  


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Question 4
Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [12]:
import numpy as np

Baghel = np.linspace(10, 100, 25)

print("Array:", Baghel)
print("Dimensions:", Baghel.ndim) 
print("Shape:", Baghel.shape)  
print("Total Elements:", Baghel.size)  
print("Data Type of Elements:", Baghel.dtype)  
print("Total Bytes Consumed:", Baghel.nbytes)  


transposed_array = Baghel.reshape(25, 1)
print("\nTransposed using reshape():\n", transposed_array)

print("\nTransposed using .T:\n", Baghel.T) 

print("\nIs reshaped array same as .T? :", np.array_equal(transposed_array, Baghel.T))


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type of Elements: float64
Total Bytes Consumed: 200

Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Is reshaped array same as .T? : False


Question 5 
Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [13]:
ucs420_Baghel = np.array([
    [10, 20, 30, 40], 
    [50, 60, 70, 80], 
    [90, 15, 20, 35]
])

# Step 2: Compute statistics
mean_value = np.mean(ucs420_Baghel)     
median_value = np.median(ucs420_Baghel)  
max_value = np.max(ucs420_Baghel)        
min_value = np.min(ucs420_Baghel)         
unique_values = np.unique(ucs420_Baghel)  

reshaped_ucs420_Baghel = ucs420_Baghel.reshape(4, 3)


resized_ucs420_Baghel = np.resize(ucs420_Baghel, (2, 3))

# Step 5: Print results
print("Original 3x4 Array (ucs420_Baghel):\n", ucs420_Baghel)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max Value:", max_value)
print("Min Value:", min_value)
print("Unique Elements:", unique_values)

print("\nReshaped (4x3) Array:\n", reshaped_ucs420_Baghel)
print("\nResized (2x3) Array:\n", resized_ucs420_Baghel)


Original 3x4 Array (ucs420_Baghel):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3) Array:
 [[10 20 30]
 [40 50 60]]
